export const institutions = [
    {
      id: 1,
      name: "পাঞ্চগড় সরকারি কলেজ",
      type: "college",
      location: "sadar",
      address: "কলেজ রোড, পাঞ্চগড় সদর",
      phone: "০১৭১২-৩৪৫৬৭৮",
      email: "panchagarh.gov.college@gmail.com",
      website: "https://pgc.edu.bd",
      rating: 4.5,
      image: "/placeholder.svg?key=qaaf3",
      description:
        "পাঞ্চগড় সরকারি কলেজ ১৯৬৯ সালে প্রতিষ্ঠিত হয়। এটি পাঞ্চগড় জেলার একটি প্রধান উচ্চ শিক্ষা প্রতিষ্ঠান। এখানে বিজ্ঞান, কলা ও বাণিজ্য বিভাগে উচ্চ মাধ্যমিক ও স্নাতক পর্যায়ে শিক্ষা প্রদান করা হয়।",
      courses: ["বিজ্ঞান", "কলা", "বাণিজ্য", "সমাজবিজ্ঞান", "ইংরেজি"],
    },
    {
      id: 2,
      name: "পাঞ্চগড় সরকারি উচ্চ বিদ্যালয়",
      type: "school",
      location: "sadar",
      address: "স্কুল রোড, পাঞ্চগড় সদর",
      phone: "০১৭১৩-৪৫৬৭৮৯",
      email: "panchagarh.gov.school@gmail.com",
      website: "https://pgs.edu.bd",
      rating: 4.2,
      image: "/traditional-schoolhouse.png",
      description:
        "পাঞ্চগড় সরকারি উচ্চ বিদ্যালয় ১৯৫৫ সালে প্রতিষ্ঠিত হয়। এটি পাঞ্চগড় জেলার একটি প্রধান শিক্ষা প্রতিষ্ঠান। এখানে ষষ্ঠ শ্রেণি থেকে দশম শ্রেণি পর্যন্ত শিক্ষা প্রদান করা হয়।",
      courses: ["বিজ্ঞান", "মানবিক", "ব্যবসায় শিক্ষা"],
    },
    {
      id: 3,
      name: "বোদা সরকারি কলেজ",
      type: "college",
      location: "boda",
      address: "কলেজ পাড়া, বোদা",
      phone: "০১৭১৪-৫৬৭৮৯০",
      email: "boda.gov.college@gmail.com",
      website: "https://bodacollege.edu.bd",
      rating: 4.0,
      image: "/vibrant-college-campus.png",
      description:
        "বোদা সরকারি কলেজ ১৯৮৫ সালে প্রতিষ্ঠিত হয়। এটি বোদা উপজেলার একটি প্রধান উচ্চ শিক্ষা প্রতিষ্ঠান। এখানে বিজ্ঞান, কলা ও বাণিজ্য বিভাগে উচ্চ মাধ্যমিক পর্যায়ে শিক্ষা প্রদান করা হয়।",
      courses: ["বিজ্ঞান", "কলা", "বাণিজ্য"],
    },
    {
      id: 4,
      name: "দেবীগঞ্জ সরকারি উচ্চ বিদ্যালয়",
      type: "school",
      location: "debiganj",
      address: "মেইন রোড, দেবীগঞ্জ",
      phone: "০১৭১৫-৬৭৮৯০১",
      email: "debiganj.gov.school@gmail.com",
      website: null,
      rating: 3.8,
      image: "/high-school-exterior.png",
      description:
        "দেবীগঞ্জ সরকারি উচ্চ বিদ্যালয় ১৯৬০ সালে প্রতিষ্ঠিত হয়। এটি দেবীগঞ্জ উপজেলার একটি প্রধান শিক্ষা প্রতিষ্ঠান। এখানে ষষ্ঠ শ্রেণি থেকে দশম শ্রেণি পর্যন্ত শিক্ষা প্রদান করা হয়।",
      courses: ["বিজ্ঞান", "মানবিক", "ব্যবসায় শিক্ষা"],
    },
    {
      id: 5,
      name: "তেতুলিয়া মহিলা কলেজ",
      type: "college",
      location: "tetulia",
      address: "কলেজ রোড, তেতুলিয়া",
      phone: "০১৭১৬-৭৮৯০১২",
      email: "tetulia.women.college@gmail.com",
      website: null,
      rating: 3.9,
      image: "/placeholder.svg?key=08w4m",
      description:
        "তেতুলিয়া মহিলা কলেজ ১৯৯০ সালে প্রতিষ্ঠিত হয়। এটি তেতুলিয়া উপজেলার একটি প্রধান মহিলা উচ্চ শিক্ষা প্রতিষ্ঠান। এখানে কলা ও বাণিজ্য বিভাগে উচ্চ মাধ্যমিক পর্যায়ে শিক্ষা প্রদান করা হয়।",
      courses: ["কলা", "বাণিজ্য", "গৃহ বিজ্ঞান"],
    },
    {
      id: 6,
      name: "আটোয়ারী ডিগ্রি কলেজ",
      type: "college",
      location: "atoary",
      address: "কলেজ পাড়া, আটোয়ারী",
      phone: "০১৭১৭-৮৯০১২৩",
      email: "atoary.degree.college@gmail.com",
      website: "https://adc.edu.bd",
      rating: 3.7,
      image: "/placeholder.svg?key=hez0m",
      description:
        "আটোয়ারী ডিগ্রি কলেজ ১৯৮৮ সালে প্রতিষ্ঠিত হয়। এটি আটোয়ারী উপজেলার একটি প্রধান উচ্চ শিক্ষা প্রতিষ্ঠান। এখানে বিজ্ঞান, কলা ও বাণিজ্য বিভাগে উচ্চ মাধ্যমিক ও স্নাতক পর্যায়ে শিক্ষা প্রদান করা হয়।",
      courses: ["বিজ্ঞান", "কলা", "বাণিজ্য", "সমাজবিজ্ঞান"],
    },
    {
      id: 7,
      name: "পাঞ্চগড় টেকনিক্যাল স্কুল এন্ড কলেজ",
      type: "college",
      location: "sadar",
      address: "টেকনিক্যাল মোড়, পাঞ্চগড় সদর",
      phone: "০১৭১৮-৯০১২৩৪",
      email: "panchagarh.tsc@gmail.com",
      website: "https://ptsc.edu.bd",
      rating: 4.3,
      image: "/placeholder.svg?key=aiize",
      description:
        "পাঞ্চগড় টেকনিক্যাল স্কুল এন্ড কলেজ ১৯৮০ সালে প্রতিষ্ঠিত হয়। এটি পাঞ্চগড় জেলার একটি প্রধান কারিগরি শিক্ষা প্রতিষ্ঠান। এখানে এসএসসি ও এইচএসসি ভোকেশনাল কোর্স পরিচালনা করা হয়।",
      courses: ["ইলেকট্রিক্যাল", "ইলেকট্রনিক্স", "সিভিল", "মেকানিক্যাল", "কম্পিউটার"],
    },
    {
      id: 8,
      name: "বোদা মহিলা ডিগ্রি কলেজ",
      type: "college",
      location: "boda",
      address: "কলেজ রোড, বোদা",
      phone: "০১৭১৯-০১২৩৪৫",
      email: "boda.women.college@gmail.com",
      website: null,
      rating: 3.6,
      image: "/placeholder.svg?key=9v2do",
      description:
        "বোদা মহিলা ডিগ্রি কলেজ ১৯৯২ সালে প্রতিষ্ঠিত হয়। এটি বোদা উপজেলার একটি প্রধান মহিলা উচ্চ শিক্ষা প্রতিষ্ঠান। এখানে কলা ও বাণিজ্য বিভাগে উচ্চ মাধ্যমিক ও স্নাতক পর্যায়ে শিক্ষা প্রদান করা হয়।",
      courses: ["কলা", "বাণিজ্য", "গৃহ বিজ্ঞান", "সমাজকর্ম"],
    },
    {
      id: 9,
      name: "পাঞ্চগড় আলিম মাদ্রাসা",
      type: "madrasa",
      location: "sadar",
      address: "মাদ্রাসা রোড, পাঞ্চগড় সদর",
      phone: "০১৭২০-১২৩৪৫৬",
      email: "panchagarh.alim.madrasa@gmail.com",
      website: null,
      rating: 3.8,
      image: "/placeholder.svg?height=300&width=500&query=madrasa",
      description:
        "পাঞ্চগড় আলিম মাদ্রাসা ১৯৭৫ সালে প্রতিষ্ঠিত হয়। এটি পাঞ্চগড় জেলার একটি প্রধান ইসলামিক শিক্ষা প্রতিষ্ঠান। এখানে দাখিল ও আলিম পর্যায়ে শিক্ষা প্রদান করা হয়।",
      courses: ["হিফজুল কুরআন", "আরবি", "ফিকাহ", "হাদিস", "তাফসির"],
    },
    {
      id: 10,
      name: "তেতুলিয়া সরকারি উচ্চ বিদ্যালয়",
      type: "school",
      location: "tetulia",
      address: "স্কুল রোড, তেতুলিয়া",
      phone: "০১৭২১-২৩৪৫৬৭",
      email: "tetulia.gov.school@gmail.com",
      website: "https://tgs.edu.bd",
      rating: 4.1,
      image: "/high-school-exterior.png",
      description:
        "তেতুলিয়া সরকারি উচ্চ বিদ্যালয় ১৯৬৫ সালে প্রতিষ্ঠিত হয়। এটি তেতুলিয়া উপজেলার একটি প্রধান শিক্ষা প্রতিষ্ঠান। এখানে ষষ্ঠ শ্রেণি থেকে দশম শ্রেণি পর্যন্ত শিক্ষা প্রদান করা হয়।",
      courses: ["বিজ্ঞান", "মানবিক", "ব্যবসায় শিক্ষা"],
    },
    {
      id: 11,
      name: "দেবীগঞ্জ ডিগ্রি কলেজ",
      type: "college",
      location: "debiganj",
      address: "কলেজ রোড, দেবীগঞ্জ",
      phone: "০১৭২২-৩৪৫৬৭৮",
      email: "debiganj.degree.college@gmail.com",
      website: "https://ddc.edu.bd",
      rating: 3.9,
      image: "/placeholder.svg?key=yckz3",
      description:
        "দেবীগঞ্জ ডিগ্রি কলেজ ১৯৮২ সালে প্রতিষ্ঠিত হয়। এটি দেবীগঞ্জ উপজেলার একটি প্রধান উচ্চ শিক্ষা প্রতিষ্ঠান। এখানে বিজ্ঞান, কলা ও বাণিজ্য বিভাগে উচ্চ মাধ্যমিক ও স্নাতক পর্যায়ে শিক্ষা প্রদান করা হয়।",
      courses: ["বিজ্ঞান", "কলা", "বাণিজ্য", "সমাজবিজ্ঞান"],
    },
    {
      id: 12,
      name: "আটোয়ারী সরকারি উচ্চ বিদ্যালয়",
      type: "school",
      location: "atoary",
      address: "স্কুল রোড, আটোয়ারী",
      phone: "০১৭২৩-৪৫৬৭৮৯",
      email: "atoary.gov.school@gmail.com",
      website: null,
      rating: 3.7,
      image: "/high-school-exterior.png",
      description:
        "আটোয়ারী সরকারি উচ্চ বিদ্যালয় ১৯৭০ সালে প্রতিষ্ঠিত হয়। এটি আটোয়ারী উপজেলার একটি প্রধান শিক্ষা প্রতিষ্ঠান। এখানে ষষ্ঠ শ্রেণি থেকে দশম শ্রেণি পর্যন্ত শিক্ষা প্রদান করা হয়।",
      courses: ["বিজ্ঞান", "মানবিক", "ব্যবসায় শিক্ষা"],
    },
  ]
  